[2025-03-12 20:56:27,602] #DEBUG conf.py (49): logger active
[2025-03-12 20:56:27,699] #DEBUG conf_redis.py (14): Установленно соединение с Redis
[2025-03-12 20:56:27,703] #DEBUG conf_redis.py (14): Установленно соединение с Redis
[2025-03-12 20:56:58,404] #ERROR set_mongodb.py (32): Ошибка подключения к MongoDB: mongo-bot:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67d1cacb9916a2c7ec0ca16b, topology_type: Unknown, servers: [<ServerDescription ('mongo-bot', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo-bot:27017: [Errno 11001] getaddrinfo failed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
